### ISSUE TITLE
create imageViews programmatically

### ISSUE THREAD

**Issue by mustafaozhan** [halilozel1903/CatchTheFruits#2]
Merhaba Halil,

Guzel bi uygulama olmus eline saglik. Yalniz GridView ve birden cok ImageView kullanmak yerine herhangi bi layout (Relative/Linear/Constraint) kullanip icerisinde Image view i Kotlin/Java kodu ile calisma aninda olusturabilirsin. Boylece daha performansli ve profesyonel olur. Senin icin de iyi bi pratik olur,

Eger goz atmak istersen ornegi [burada](https://github.com/mustafaozhan/POSSystem/blob/master/app/src/main/java/tr/com/wiki/possystem/ui/fragments/SectionFragment.kt) mevcut. Ornekte bir restorantta serverdan gelen  masa, masa duzeni, masanin sekli, pozisyonu ve boyutuna gore ekrana calisma zamaninda nasil olusturulup ekrana nasil koyulacagi mevcut. Sende random bir pozisyon atayarak projende kullanabilirsin.

**Comment by halilozel1903** [comment]
Anladım teşekkür ederim :) ben bir bakayım
